# Site settings
title: Silvio Moreto
email: silviomoreto@gmail.com
description: "I am Silvio Moreto. Main knowledge areas are Web developer in django and python, Front end developer, and Image processing"
twitter_username: silviomoreto
github_username:  silviomoreto

# Build settings
markdown: kramdown
permalink: pretty
